# Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
# This file is available under the MIT license.

language: go

go:
- 1.6

before_install:
- go get github.com/onsi/gomega
- go get github.com/onsi/ginkgo
- go get golang.org/x/tools/cmd/cover

script:
- ./go_test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
